version: '3.8'

services:
  dev-app:
    image: node:20.9.0
    container_name: clean-ddd-api
    working_dir: /app
    volumes:
      - ../../src:/app/src
      - ../../package.json:/app/package.json
      - ../../yarn.lock:/app/yarn.lock
      - ../../tsconfig.json:/app/tsconfig.json
    command: bash -c "yarn install && yarn start:dev"
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - ENV=development
      - PROTOCOL=http
      - BASE_URL=localhost
      - JWT_SECRET=development-secret-key
      - JWT_EXPIRES_IN=24h
      - ADMIN_IDENTIFIER=admin@admin.fr
      - ADMIN_PASSWORD=admin
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
