name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Conventions
        run: yarn check:conventions

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Unit tests
        run: yarn test:units

      - name: End-to-end tests
        run: yarn test:e2e
