name: ci

on:
  push:
    branches:
      - main
      - '[0-9]+.x'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Deps
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint

      - name: Units Test
        run: |
          npm run test:units
